apiVersion: apps/v1
kind: Deployment
metadata: 
  name: kube-postgre
spec:
  selector:
    matchLabels:
      app: kube-postgre
  template:
    metadata:
      labels:
        app: kube-postgre
    spec:
      containers:
        - name: kube-postgre
          image: postgres:bullseye
          ports: 
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "root"
            - name: POSTGRES_USER
              value: "root"
            - name: POSTGRES_DB
              value: "kubenews"

---

apiVersion: v1
kind: Service
metadata:
  name: kube-postgre-service
spec:
  selector: 
    app: kube-postgre
  ports:
    - port: 5432
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: kube-news-app
spec: 
  selector:
    matchLabels:
      app: kube-news-app
  template:
    metadata:
      labels:
        app: kube-news-app
    spec: 
      containers:
        - name: kube-news-app
          image: yurimetal/kubenews:v2
          ports:
            - containerPort: 8080
          env: 
            - name: DB_DATABASE
              value: kubenews
            - name: DB_HOST
              value: kube-postgre-service
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: root

---

apiVersion: v1
kind: Service
metadata:
  name: kube-news-app-service
spec:
  selector:
    app: kube-news-app
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30002
